[project]
name = "portfolio-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sushil Chand", email = "sushilchand@Sushils-MacBook-Air.local" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "groq>=1.7.0",
    "pre-commit>=4.6.2",
    "pydantic>=2.13.5",
    "pypdf>=6.19.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "uvicorn>=0.53.0",
]

[project.scripts]
portfolio-backend = "portfolio_backend:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
